"""
Manual Mics — Hardcoded Open Mic Data

This is our "source of truth" for mics that we know about from personal
experience, word of mouth, or research. These don't come from scrapers —
they're hand-entered and verified.

Each mic is a dictionary (dict) with keys matching the open_mics table columns.
We only include the fields we actually have info for — the database will
fill in defaults (like urgency='normal') for anything we leave out.

The seed_database() function at the bottom checks if the DB is empty and
populates it. It's safe to call repeatedly — it only seeds ONCE.
"""

from utils.database import seed_mics, is_db_empty

# ===========================================================================
# ALL NYC OPEN MICS — Organized by day of week
# ===========================================================================

MANUAL_MICS = [

    # -----------------------------------------------------------------------
    # MONDAY
    # -----------------------------------------------------------------------
    {
        "name": "Halyards",
        "venue": "Halyards",
        "address": "406 3rd Ave",
        "neighborhood": "Gowanus",
        "borough": "Brooklyn",
        "day_of_week": "Monday",
        "start_time": "21:00",
        "display_time": "9:00 PM",
        "cost": "Free",
        "signup_method": "in_person",
        "urgency": "normal",
    },
    {
        "name": "Barrio Boogie",
        "venue": "Comedy In Harlem",
        "address": "508 E 117th St",
        "neighborhood": "East Harlem",
        "borough": "Manhattan",
        "day_of_week": "Monday",
        "start_time": "18:00",
        "display_time": "6:00 PM",
        "cost": "$5",
        "signup_method": "in_person",
        "urgency": "normal",
        "instagram": "@comedyinharlem",
    },

    # -----------------------------------------------------------------------
    # TUESDAY
    # -----------------------------------------------------------------------
    {
        "name": "Stand Up & Work It Out",
        "venue": "Comedy In Harlem",
        "address": "750A St Nicholas Ave",
        "neighborhood": "Harlem",
        "borough": "Manhattan",
        "day_of_week": "Tuesday",
        "start_time": "18:00",
        "display_time": "6:00 PM (signup 5pm)",
        "cost": "$5",
        "signup_method": "in_person",
        "urgency": "normal",
        "notes": "Feedback/coaching mic",
        "instagram": "@comedyinharlem",
    },
    {
        "name": "Comedians on the Loose",
        "venue": "Black Cat LES",
        "address": "172 Rivington St",
        "neighborhood": "LES",
        "borough": "Manhattan",
        "day_of_week": "Tuesday",
        "start_time": "19:30",
        "display_time": "7:30 PM",
        "cost": "$6 cash",
        "signup_method": "online",
        "signup_url": "https://www.comediansontheloose.com/open-mics",
        "urgency": "medium",
        "urgency_note": "Online slots fill up, book a few days ahead",
        "advance_days": 3,
        "instagram": "@cotlcomedy",
    },
    {
        "name": "Taco Tuesday",
        "venue": "iNine Bistro",
        "address": "53 Bruckner Blvd",
        "neighborhood": "Bronx",
        "borough": "Bronx",
        "day_of_week": "Tuesday",
        "start_time": "19:30",
        "display_time": "7:30 PM (signup 6:30pm)",
        "cost": "1 item min",
        "signup_method": "in_person",
        "urgency": "normal",
    },

    # -----------------------------------------------------------------------
    # WEDNESDAY
    # -----------------------------------------------------------------------
    {
        "name": "St. Marks Comedy Club Open Mic",
        "venue": "St. Marks Comedy Club",
        "address": "12 St Marks Pl",
        "neighborhood": "East Village",
        "borough": "Manhattan",
        "day_of_week": "Wednesday",
        "start_time": "17:30",
        "display_time": "5:30 PM",
        "signup_method": "in_person",
        "instagram": "@stmarkscomedyclub",
    },
    {
        "name": "Comedy Loves Ya",
        "venue": "EastVille Comedy Club",
        "address": "487 Atlantic Ave",
        "neighborhood": "Brooklyn",
        "borough": "Brooklyn",
        "day_of_week": "Wednesday",
        "start_time": "18:00",
        "display_time": "6:00 PM",
        "cost": "1 drink min",
        "signup_method": "in_person",
        "signup_notes": "Sign up in person 30 min before showtime",
        "instagram": "@eastvillecomedy",
    },
    {
        "name": "Try New Sh*t",
        "venue": "EastVille Comedy Club",
        "address": "487 Atlantic Ave",
        "neighborhood": "Brooklyn",
        "borough": "Brooklyn",
        "day_of_week": "Wednesday",
        "start_time": "21:45",
        "display_time": "9:45 PM",
        "cost": "1 drink min",
        "signup_method": "in_person",
        "instagram": "@eastvillecomedy",
    },
    {
        "name": "Cuckoos Open Mic",
        "venue": "SoHo Playhouse",
        "address": "15 Vandam St",
        "neighborhood": "SoHo",
        "borough": "Manhattan",
        "day_of_week": "Wednesday",
        "start_time": "22:00",
        "display_time": "10:00 PM (doors 9:30)",
        "cost": "$5",
        "set_length_min": 7,
        "signup_method": "in_person",
        "instagram": "@cuckoos_openmic",
    },
    {
        "name": "Stand Up NY Open Mic",
        "venue": "Stand Up NY",
        "address": "236 W 78th St",
        "neighborhood": "UWS",
        "borough": "Manhattan",
        "day_of_week": "Wednesday",
        "start_time": "17:00",
        "display_time": "5:00 PM",
        "signup_method": "in_person",
        "signup_notes": "SIGN-UP IS 11am-4pm SAME DAY",
        "urgency": "high",
        "urgency_note": "List fills fast, arrive by 11am to sign up",
        "advance_days": 0,
        "instagram": "@standupny",
    },
    {
        "name": "Freddy's Bar",
        "venue": "Freddy's Bar",
        "address": "627 5th Ave",
        "neighborhood": "South Slope",
        "borough": "Brooklyn",
        "day_of_week": "Wednesday",
        "start_time": "19:30",
        "display_time": "7:30 PM",
        "cost": "Free",
        "signup_method": "in_person",
        "is_biweekly": 1,
        "urgency": "normal",
        "notes": "Every 2nd and 4th Wednesday",
    },
    {
        "name": "Cypher Open Mic",
        "venue": "Comedy In Harlem",
        "address": "750A St Nicholas Ave",
        "neighborhood": "Harlem",
        "borough": "Manhattan",
        "day_of_week": "Wednesday",
        "start_time": "20:00",
        "display_time": "8:00 PM (doors 7pm)",
        "signup_method": "in_person",
        "instagram": "@comedyinharlem",
        "notes": "Comedy, singing, poetry, storytelling",
    },
    {
        "name": "Gladys' Open Mic",
        "venue": "Comic Strip Live",
        "address": "1568 2nd Ave",
        "neighborhood": "UES",
        "borough": "Manhattan",
        "day_of_week": "Wednesday",
        "start_time": "18:00",
        "display_time": "6:00 PM",
        "signup_method": "email",
        "signup_notes": "Email gladyscomedy@yahoo.com",
        "instagram": "@thecomicstriplive",
        "urgency": "medium",
        "advance_days": 7,
    },

    # -----------------------------------------------------------------------
    # THURSDAY
    # -----------------------------------------------------------------------
    {
        "name": "Laughing Buddha",
        "venue": "St. Marks Comedy Club",
        "address": "12 St Marks Pl",
        "neighborhood": "East Village",
        "borough": "Manhattan",
        "day_of_week": "Thursday",
        "start_time": "16:30",
        "display_time": "4:30 PM",
        "signup_method": "online",
        "signup_url": "https://www.laughingbuddhacomedy.com/mics",
        "urgency": "medium",
        "advance_days": 3,
        "instagram": "@laughingbuddhacomedy",
    },
    {
        "name": "Best G.D. Open Mic",
        "venue": "EastVille Comedy Club",
        "address": "487 Atlantic Ave",
        "neighborhood": "Brooklyn",
        "borough": "Brooklyn",
        "day_of_week": "Thursday",
        "start_time": "18:00",
        "display_time": "6:00 PM",
        "cost": "1 drink min",
        "signup_method": "in_person",
        "instagram": "@eastvillecomedy",
    },
    {
        "name": "Comedy Mob",
        "venue": "NY Comedy Club",
        "address": "241 E 24th St",
        "neighborhood": "Gramercy",
        "borough": "Manhattan",
        "day_of_week": "Thursday",
        "start_time": "18:00",
        "display_time": "6:00 PM",
        "signup_method": "online",
        "signup_url": "https://www.comedymob.com",
        "urgency": "high",
        "urgency_note": "Sign-ups open Wed 10am, fill fast",
        "advance_days": 1,
        "instagram": "@comedymobnyc",
    },
    {
        "name": "SoHo Playhouse Thursday Mic",
        "venue": "SoHo Playhouse",
        "address": "15 Vandam St",
        "neighborhood": "SoHo",
        "borough": "Manhattan",
        "day_of_week": "Thursday",
        "start_time": "23:00",
        "display_time": "11:00 PM (doors 10:30)",
        "cost": "Free",
        "signup_method": "instagram_dm",
        "signup_notes": "DM @matt_scribble on IG, list goes out at 9pm",
        "instagram": "@sohoplayhousenyc",
    },
    {
        "name": "Black Cat LES 7pm",
        "venue": "Black Cat LES",
        "address": "172 Rivington St",
        "neighborhood": "LES",
        "borough": "Manhattan",
        "day_of_week": "Thursday",
        "start_time": "19:00",
        "display_time": "7:00 PM",
        "cost": "$6 cash",
        "signup_method": "online",
        "signup_url": "https://www.comediansontheloose.com/open-mics",
        "urgency": "medium",
        "advance_days": 3,
        "instagram": "@cotlcomedy",
    },
    {
        "name": "Black Cat LES 9pm",
        "venue": "Black Cat LES",
        "address": "172 Rivington St",
        "neighborhood": "LES",
        "borough": "Manhattan",
        "day_of_week": "Thursday",
        "start_time": "21:00",
        "display_time": "9:00 PM",
        "cost": "$6 cash",
        "signup_method": "online",
        "signup_url": "https://www.comediansontheloose.com/open-mics",
        "urgency": "medium",
        "advance_days": 3,
        "instagram": "@cotlcomedy",
    },

    # -----------------------------------------------------------------------
    # FRIDAY
    # -----------------------------------------------------------------------
    {
        "name": "Laughing Buddha",
        "venue": "St. Marks Comedy Club",
        "address": "12 St Marks Pl",
        "neighborhood": "East Village",
        "borough": "Manhattan",
        "day_of_week": "Friday",
        "start_time": "16:30",
        "display_time": "4:30 PM",
        "signup_method": "online",
        "signup_url": "https://www.laughingbuddhacomedy.com/mics",
        "advance_days": 3,
        "instagram": "@laughingbuddhacomedy",
    },
    {
        "name": "Golden Pen Mic",
        "venue": "EastVille Comedy Club",
        "address": "487 Atlantic Ave",
        "neighborhood": "Brooklyn",
        "borough": "Brooklyn",
        "day_of_week": "Friday",
        "start_time": "17:30",
        "display_time": "5:30 PM",
        "cost": "1 drink min",
        "signup_method": "in_person",
        "instagram": "@eastvillecomedy",
    },
    {
        "name": "Stand Up NY Open Mic",
        "venue": "Stand Up NY",
        "address": "236 W 78th St",
        "neighborhood": "UWS",
        "borough": "Manhattan",
        "day_of_week": "Friday",
        "start_time": "17:00",
        "display_time": "5:00 PM",
        "signup_method": "in_person",
        "signup_notes": "SIGN-UP IS 11am-4pm SAME DAY",
        "urgency": "high",
        "advance_days": 0,
        "instagram": "@standupny",
    },
    {
        "name": "Black Cat LES 7pm",
        "venue": "Black Cat LES",
        "address": "172 Rivington St",
        "neighborhood": "LES",
        "borough": "Manhattan",
        "day_of_week": "Friday",
        "start_time": "19:00",
        "display_time": "7:00 PM",
        "cost": "$6 cash",
        "signup_method": "online",
        "signup_url": "https://www.comediansontheloose.com/open-mics",
        "advance_days": 3,
        "instagram": "@cotlcomedy",
    },
    {
        "name": "Black Cat LES 9pm",
        "venue": "Black Cat LES",
        "address": "172 Rivington St",
        "neighborhood": "LES",
        "borough": "Manhattan",
        "day_of_week": "Friday",
        "start_time": "21:00",
        "display_time": "9:00 PM",
        "cost": "$6 cash",
        "signup_method": "online",
        "signup_url": "https://www.comediansontheloose.com/open-mics",
        "advance_days": 3,
        "instagram": "@cotlcomedy",
    },
    {
        "name": "Late Night Open Mic",
        "venue": "EastVille Comedy Club",
        "address": "487 Atlantic Ave",
        "neighborhood": "Brooklyn",
        "borough": "Brooklyn",
        "day_of_week": "Friday",
        "start_time": "23:30",
        "display_time": "11:30 PM",
        "cost": "1 drink min",
        "signup_method": "in_person",
        "instagram": "@eastvillecomedy",
    },
    {
        "name": "Gladys' Open Mic",
        "venue": "Comic Strip Live",
        "address": "1568 2nd Ave",
        "neighborhood": "UES",
        "borough": "Manhattan",
        "day_of_week": "Friday",
        "start_time": "18:00",
        "display_time": "6:00 PM",
        "signup_method": "email",
        "signup_notes": "Email gladyscomedy@yahoo.com",
        "advance_days": 7,
        "instagram": "@thecomicstriplive",
    },

    # -----------------------------------------------------------------------
    # SATURDAY
    # -----------------------------------------------------------------------
    {
        "name": "Lifeboat Mic",
        "venue": "SoHo Playhouse",
        "address": "15 Vandam St",
        "neighborhood": "SoHo",
        "borough": "Manhattan",
        "day_of_week": "Saturday",
        "start_time": "15:00",
        "display_time": "3:00 PM",
        "cost": "Free",
        "set_length_min": 5,
        "signup_method": "in_person",
        "instagram": "@sohoplayhousenyc",
    },
    {
        "name": "EastVille Open Mic",
        "venue": "EastVille Comedy Club",
        "address": "487 Atlantic Ave",
        "neighborhood": "Brooklyn",
        "borough": "Brooklyn",
        "day_of_week": "Saturday",
        "start_time": "16:00",
        "display_time": "4:00 PM",
        "cost": "1 drink min",
        "signup_method": "in_person",
        "instagram": "@eastvillecomedy",
    },
    {
        "name": "Black Cat LES 7pm",
        "venue": "Black Cat LES",
        "address": "172 Rivington St",
        "neighborhood": "LES",
        "borough": "Manhattan",
        "day_of_week": "Saturday",
        "start_time": "19:00",
        "display_time": "7:00 PM",
        "cost": "$6 cash",
        "signup_method": "online",
        "signup_url": "https://www.comediansontheloose.com/open-mics",
        "advance_days": 3,
        "instagram": "@cotlcomedy",
    },
    {
        "name": "Black Cat LES 9pm",
        "venue": "Black Cat LES",
        "address": "172 Rivington St",
        "neighborhood": "LES",
        "borough": "Manhattan",
        "day_of_week": "Saturday",
        "start_time": "21:00",
        "display_time": "9:00 PM",
        "cost": "$6 cash",
        "signup_method": "online",
        "signup_url": "https://www.comediansontheloose.com/open-mics",
        "advance_days": 3,
        "instagram": "@cotlcomedy",
    },
    {
        "name": "Late Night Open Mic",
        "venue": "EastVille Comedy Club",
        "address": "487 Atlantic Ave",
        "neighborhood": "Brooklyn",
        "borough": "Brooklyn",
        "day_of_week": "Saturday",
        "start_time": "23:30",
        "display_time": "11:30 PM",
        "cost": "1 drink min",
        "signup_method": "in_person",
        "instagram": "@eastvillecomedy",
    },

    # -----------------------------------------------------------------------
    # SUNDAY
    # -----------------------------------------------------------------------
    {
        "name": "Golden Pen Mic",
        "venue": "EastVille Comedy Club",
        "address": "487 Atlantic Ave",
        "neighborhood": "Brooklyn",
        "borough": "Brooklyn",
        "day_of_week": "Sunday",
        "start_time": "17:00",
        "display_time": "5:00 PM",
        "cost": "1 drink min",
        "signup_method": "in_person",
        "instagram": "@eastvillecomedy",
    },
]


def seed_database():
    """
    Populates the database with our manually curated mic data.

    Only runs if the database is empty — so it's safe to call every time
    the app starts without duplicating data.
    """
    if is_db_empty():
        seed_mics(MANUAL_MICS)
        return True  # Did seed
    return False  # Already had data
